// Eigenständige LANE SWITCH Lernfälle, keine amtlichen Prüfungsfragen.
const make = (id, title, category, intro, description, from, to, question, right, wrongA, wrongB, feedback, principle, section, visual = {}) => ({
  id, title, category, intro, description, cueMs: visual.static ? 0 : 2400, durationMs:11000, motionMs:6500,
  hazard:{from,to,rx:76,ry:78,...visual.hitArea}, question,
  options:[{id:'safe',text:right,correct:true},{id:'risk-a',text:wrongA,correct:false},{id:'risk-b',text:wrongB,correct:false}],
  feedback, principle, source:{label:`StVO ${section === 'anlage_2' ? 'Anlage 2 · Zeichen 206 / Haltlinie' : '§ '+section}`,url:`https://www.gesetze-im-internet.de/stvo_2013/${section === 'anlage_2' ? section : '__'+section}.html`}, visual
});
export const MORE_SCENES = [
  make('braking','Bremslichter voraus','Abstand',
    'Du folgst einem Auto im Stadtverkehr. Beobachte auch den Verkehr davor.',
    'Auf deinem Fahrstreifen fährt ein blaues Auto. Seine beiden Bremslichter und die dritte Bremsleuchte leuchten auf; das Auto wird langsamer.',
    [436,344],[449,379], 'Das Auto vor dir bremst. Was tust du?',
    'Frühzeitig verzögern und genügend Abstand zum Anhalten halten.', 'Dicht auffahren, damit niemand einschert.', 'Ohne Blick nach hinten sofort ausscheren.',
    'Ein ausreichender Abstand lässt dir auch bei plötzlichem Bremsen Raum zum Anhalten. Beobachte die Verkehrsentwicklung weiter vorn.',
    'Abstand schafft Zeit zum Handeln.', '4'),
  make('obstacle','Engstelle mit Gegenverkehr','Begegnungsverkehr',
    'Ein Lieferwagen steht auf deiner Fahrbahnseite. Es gibt keine Zeichen, die den Vorrang an der Engstelle regeln.',
    'Rechts blockiert ein Lieferwagen deinen Fahrweg. Auf der linken Gegenfahrbahn nähert sich ein weißes Auto mit sichtbaren Scheinwerfern.',
    [299,302],[262,374], 'Du müsstest zum Vorbeifahren nach links ausscheren. Wie reagierst du?',
    'Vor dem Hindernis warten und den Gegenverkehr durchfahren lassen.', 'Beschleunigen, um zuerst in die Engstelle zu kommen.', 'Den Gegenverkehr durch Hupen zum Warten bringen.',
    'Zum Vorbeifahren an deinem Hindernis müsstest du den Gegenverkehrsraum nutzen. Lass das entgegenkommende Auto durch; prüfe vor dem Ausscheren auch den Verkehr hinter dir.',
    'Erkenne zuerst, wem der benötigte Platz gerade gehört.', '6'),
  make('bus-warning','Bus mit Warnblinklicht','Öffentliche Verkehrsmittel',
    'Ein Linienbus hält an einer gekennzeichneten Haltestelle. Sein Warnblinklicht ist eingeschaltet.',
    'Rechts steht ein Bus neben einem Haltestellenschild. Beide gelben Blinkleuchten leuchten. Eine Person tritt neben dem Bus hervor.',
    [518,357],[487,367], 'Wie fährst du an diesem haltenden Bus vorbei?',
    'Nur mit Schrittgeschwindigkeit und ohne Fahrgäste zu gefährden oder zu behindern; nötigenfalls warten.', 'Mit normalem Tempo, solange niemand auf deiner Fahrbahn steht.', 'Beschleunigen, damit die Fahrgäste nicht warten müssen.',
    'Beim haltenden Linienbus mit Warnblinklicht ist besondere Vorsicht nötig: Fahrgäste können unvermittelt hervortreten. Schrittgeschwindigkeit gilt hier auch für den Gegenverkehr auf derselben Fahrbahn.',
    'Rechne mit Menschen, die das große Fahrzeug verdeckt.', '20',{static:true,hitArea:{also:[{x:589,y:320,rx:76,ry:108}]}}),
  make('bus-departure','Der Bus fährt an','Öffentliche Verkehrsmittel',
    'Du näherst dich einem Linienbus an einer gekennzeichneten Haltestelle.',
    'Der Bus rechts setzt seinen linken Blinker und beginnt, sich aus der Haltestelle zur Fahrbahn hin zu bewegen.',
    [565,367],[510,366], 'Der Linienbus möchte abfahren. Was ist sinnvoll?',
    'Tempo verringern und das Abfahren ermöglichen; nötigenfalls warten.', 'Schnell vorbeiziehen, bevor er ausschert.', 'Dicht daneben bleiben, weil du schon auf der Straße bist.',
    'Ermögliche dem Linienbus das Abfahren von der gekennzeichneten Haltestelle. Frühzeitiges Verzögern entschärft den Konflikt.',
    'Ein Blinker kündigt den nächsten Raumbedarf an.', '20'),
  make('railway','Am Bahnübergang','Schienenverkehr',
    'Du näherst dich einem Bahnübergang mit Andreaskreuz und Lichtzeichen.',
    'Vor dir verlaufen Gleise quer über die Straße. Rechts am Andreaskreuz leuchtet ein rotes Licht auf; die Schranke ist noch offen.',
    [628,284],[628,284], 'Das rote Licht leuchtet, die Schranke ist noch oben. Was tust du?',
    'Vor dem Andreaskreuz anhalten und warten.', 'Noch hindurchfahren, solange die Schranke oben ist.', 'Erst warten, wenn ein Zug sichtbar ist.',
    'Bereits das rote Licht verlangt Warten. Eine offene Schranke bedeutet jetzt keine freie Durchfahrt.',
    'Reagiere auf die Warnung, bevor die Gefahr direkt vor dir ist.', '19'),
  make('left-turn','Links abbiegen','Gegenverkehr beim Abbiegen',
    'Du willst links abbiegen und blinkst links. Es gibt keine Ampel, die dir einen geschützten Abbiegevorgang freigibt.',
    'Eine Straße zweigt links ab. Ein Motorrad kommt dir auf der linken Gegenfahrbahn entgegen und fährt geradeaus.',
    [304,289],[271,357], 'Das Motorrad kommt dir entgegen. Wie biegst du links ab?',
    'Das Motorrad durchfahren lassen und erst bei freiem Weg abbiegen.', 'Noch vor dem Motorrad abbiegen, weil es schmal ist.', 'Abbiegen, weil du bereits blinkst.',
    'Beim Linksabbiegen musst du entgegenkommende Fahrzeuge durchfahren lassen. Die schmale Silhouette eines Motorrads kann seine Annäherung schwerer erkennbar machen.',
    'Klein im Blickfeld heißt nicht weit entfernt.', '9'),
  make('turn-pedestrian','Menschen beim Abbiegen','Fußverkehr',
    'Du willst rechts in eine Seitenstraße abbiegen. Dort gibt es keinen Zebrastreifen.',
    'Eine Person überquert gerade die Seitenstraße, in die du rechts abbiegen möchtest. Sie bewegt sich von rechts in deinen Abbiegeweg.',
    [659,309],[580,309], 'Eine Person überquert deinen Abbiegeweg. Was tust du?',
    'Warten und die Person sicher überqueren lassen.', 'Hupen und abbiegen, weil kein Zebrastreifen da ist.', 'Knapp hinter der Person durchfahren, ohne langsamer zu werden.',
    'Beim Abbiegen musst du auf zu Fuß Gehende besonders Rücksicht nehmen und nötigenfalls warten. Dafür ist kein Zebrastreifen erforderlich.',
    'Prüfe den gesamten Abbiegeweg.', '9'),
  make('driveway','Ausfahrt am Gehweg','Fehler anderer auffangen',
    'Du fährst geradeaus. Rechts liegen Grundstücksausfahrten hinter einem durchgehenden Gehweg.',
    'Ein Auto bewegt sich aus einer Einfahrt rechts über den Gehweg auf die Straße zu. Eine Mauer schränkt die Sicht der fahrenden Person ein.',
    [665,335],[566,346], 'Das Auto rollt aus der Einfahrt. Was ist vorausschauend?',
    'Tempo reduzieren, bremsbereit bleiben und nötigenfalls anhalten.', 'Unverändert fahren, weil das Auto warten müsste.', 'Sofort ohne Verkehrsbeobachtung nach links ausweichen.',
    'Wer aus einem Grundstück einfährt, muss eine Gefährdung anderer ausschließen. Rechne trotzdem mit einem Fehler und sichere deinen Handlungsspielraum.',
    'Vorrang verhindert keinen Zusammenstoß von allein.', '10'),
  make('stop-sign','Halt vor der Kreuzung','Verkehrszeichen',
    'Du näherst dich einer Kreuzung mit Stoppschild und Haltlinie. Es gibt keine Ampel.',
    'Rechts steht ein achteckiges rotes STOP-Schild. Eine breite weiße Haltlinie liegt vor der Kreuzung. Der Querverkehr ist momentan nicht zu sehen.',
    [635,287],[635,287], 'Die Kreuzung wirkt frei. Was verlangt die Situation?',
    'An der Haltlinie vollständig anhalten, Vorfahrt beachten und die Sicht prüfen.', 'Langsam weiterrollen, wenn gerade niemand zu sehen ist.', 'Nur anhalten, wenn ein anderes Fahrzeug hupt.',
    'Das Stoppschild verlangt vollständiges Anhalten und Vorfahrtgewähren. Reicht die Sicht von der Haltlinie nicht, taste dich anschließend vorsichtig vor und warte bei Bedarf erneut.',
    'Eine freie Momentaufnahme ersetzt den vorgeschriebenen Halt nicht.', 'anlage_2',{static:true}),
  make('red-light','Rot bleibt Rot','Lichtzeichen',
    'Du näherst dich einer Ampelkreuzung. Es gibt keinen Grünpfeil.',
    'Die Ampel rechts vor der Kreuzung zeigt oben Rot. Eine weiße Haltlinie liegt vor dir.',
    [631,267],[631,267], 'Die Ampel zeigt Rot, die Kreuzung scheint frei. Was tust du?',
    'Vor der Haltlinie anhalten und die Freigabe abwarten.', 'Vorsichtig weiterfahren, wenn niemand kommt.', 'Nach kurzem Halt ohne Freigabe weiterfahren.',
    'Rot ordnet Halt vor der Kreuzung an. Eine scheinbar freie Straße erlaubt das Überfahren nicht.',
    'Sichtbare Freiheit ist keine Freigabe.', '37',{static:true}),
  make('blocked-junction','Grün, aber kein Platz','Verkehrsfluss',
    'Deine Ampel zeigt Grün. Hinter der Kreuzung stockt der Verkehr.',
    'Hinter der Kreuzung stehen mehrere Autos dicht hintereinander. Das letzte steht direkt am Kreuzungsausgang; du könntest die Kreuzung nicht vollständig räumen.',
    [421,290],[421,290], 'Die Ampel ist grün, hinter der Kreuzung fehlt Platz. Wie reagierst du?',
    'Vor der Kreuzung warten, bis dahinter genügend Platz frei ist.', 'Einfahren und mitten auf der Kreuzung warten.', 'Dicht auffahren, damit dich niemand überholt.',
    'Fahre bei stockendem Verkehr auch mit Grün nicht ein, wenn du auf der Kreuzung warten müsstest.',
    'Plane auch den Platz hinter deinem nächsten Fahrweg ein.', '11',{static:true}),
  make('roadworks','Arbeiten am Fahrbahnrand','Arbeitsstellen',
    'Rechts begrenzen Leitkegel eine Arbeitsstelle. Neben dem Arbeitsbereich bleibt dein Fahrstreifen frei.',
    'Eine Person in Warnkleidung bewegt sich neben den Leitkegeln und trägt ein langes Werkzeug in Richtung des freien Fahrstreifens.',
    [554,351],[505,362], 'Die Person arbeitet dicht an deinem Fahrweg. Was ist sinnvoll?',
    'Tempo reduzieren, Abstand halten und bei Bedarf warten.', 'Unverändert knapp an den Kegeln vorbeifahren.', 'Hupen und beschleunigen, damit die Person zurücktritt.',
    'Menschen und Arbeitsgeräte können über die Absperrung hinausreichen. Fahre so, dass du auf eine Bewegung in deinen Fahrweg reagieren kannst.',
    'Beobachte Bewegungsräume, nicht nur Markierungen.', '3'),
  make('deer','Wild am Waldrand','Tiere',
    'Du fährst auf einer Straße am Waldrand. Beobachte auch die Randbereiche.',
    'Ein Reh tritt rechts zwischen den Bäumen hervor und bewegt sich zum Fahrbahnrand.',
    [660,331],[562,358], 'Am Rand steht ein Reh. Wie reagierst du?',
    'Geschwindigkeit verringern, bremsbereit sein und mit weiteren Tieren rechnen.', 'Beschleunigen, bevor das Tier losläuft.', 'Sofort in den Gegenverkehr ausweichen.',
    'Das Tier kann auf die Fahrbahn laufen. Verringere das Tempo, halte das Fahrzeug unter Kontrolle und beobachte beide Ränder weiter.',
    'Ein Tier kann weitere Tiere ankündigen.', '3',{rural:true}),
  make('horse','An einem Pferd vorbei','Unberechenbare Bewegungen',
    'Vor dir wird rechts am Fahrbahnrand ein Pferd geführt.',
    'Das Pferd und die führende Person gehen rechts vor dir. Das Pferd bewegt den Kopf zur Fahrbahnmitte und macht einen kleinen Schritt nach links.',
    [568,353],[540,357], 'Wie näherst du dich dem Pferd?',
    'Langsam und mit viel Abstand; erst bei genügend Platz ruhig vorbeifahren.', 'Hupen und dicht vorbeifahren.', 'Den Motor aufheulen lassen, damit das Pferd Platz macht.',
    'Pferde können erschrecken und seitlich ausweichen. Vermeide unnötigen Lärm und lasse genügend Raum; warte, wenn ein sicheres Vorbeifahren nicht möglich ist.',
    'Passe deine Annäherung an das Verhalten anderer an.', '1',{rural:true}),
  make('wet-road','Wasser auf der Fahrbahn','Wetter und Haftung',
    'Es regnet. Vor dir sammelt sich Wasser auf der Fahrbahn.',
    'Eine große Wasserfläche liegt auf deinem Fahrstreifen. Regentropfen sind sichtbar, die Fahrbahn glänzt.',
    [446,382],[446,382], 'Wie reagierst du auf die Wasserfläche?',
    'Frühzeitig Tempo reduzieren und abrupte Lenk- oder Bremsbewegungen vermeiden.', 'Mit höherem Tempo durchfahren.', 'Direkt in der Wasserfläche scharf lenken.',
    'Stehendes Wasser kann den Kontakt der Reifen zur Straße beeinträchtigen. Reduziere das Tempo rechtzeitig vor der Stelle.',
    'Passe das Tempo vor der kritischen Stelle an.', '3',{rural:true,static:true}),
  make('fog','Nebel voraus','Sichtweite',
    'Du fährst auf einer Landstraße. Vor dir zieht eine dichte Nebelbank über die Fahrbahn.',
    'Die Straße und die Bäume verschwinden voraus in einer hellgrauen Nebelbank. Der weitere Verlauf ist kaum zu erkennen.',
    [390,275],[390,275], 'Die Sicht wird deutlich schlechter. Was tust du?',
    'Geschwindigkeit an die Sicht anpassen und genügend Abstand halten.', 'Am Tempo des vorausfahrenden Autos orientieren und dicht folgen.', 'Weiterfahren wie zuvor, weil du die Strecke kennst.',
    'Fahre so, dass du innerhalb der übersehbaren Strecke anhalten kannst. Die vertraute Strecke ersetzt die fehlende Sicht nicht.',
    'Deine Sicht bestimmt deinen Handlungsspielraum.', '3',{rural:true,static:true}),
  make('overtake-cycle','Überholen braucht Platz','Radverkehr und Abstand',
    'Du folgst innerorts einem Fahrrad. Zum Überholen müsstest du auf die Gegenfahrbahn fahren.',
    'Rechts vor dir fährt ein Fahrrad. Ein Auto kommt auf der Gegenfahrbahn näher. Zwischen Auto und Fahrrad bleibt zu wenig Raum zum sicheren Überholen.',
    [304,298],[264,374], 'Gegenverkehr und Fahrrad lassen zu wenig Platz. Wie reagierst du?',
    'Hinter dem Fahrrad bleiben und eine sichere Überholmöglichkeit abwarten.', 'Mit wenig Seitenabstand zwischen beiden durchfahren.', 'Hupen, damit das Fahrrad auf den Gehweg fährt.',
    'Beim Überholen von Radfahrenden mit einem Kraftfahrzeug sind innerorts mindestens 1,5 Meter Seitenabstand nötig. Überhole erst, wenn auch der Gegenverkehr nicht behindert wird.',
    'Eine Lücke ist erst dann geeignet, wenn alle genug Platz haben.', '5'),
  make('reversing','Rückwärts aus der Parklücke','Rangierende Fahrzeuge',
    'Du fährst langsam auf einer öffentlichen Straße an Parkbuchten vorbei.',
    'Rechts in einer Parkbucht leuchten die weißen Rückfahrleuchten eines Lieferwagens. Sein Heck bewegt sich rückwärts zur Fahrbahn.',
    [640,362],[545,376], 'Der Lieferwagen setzt zurück. Wie reagierst du?',
    'Tempo weiter reduzieren, bremsbereit bleiben und nötigenfalls warten.', 'Dicht hinter dem Fahrzeug vorbeifahren.', 'Darauf vertrauen, dass du im Spiegel gesehen wurdest.',
    'Die Person am Steuer kann dich im Bereich hinter dem Fahrzeug übersehen. Rechne trotz ihrer besonderen Sorgfaltspflicht mit einer weiteren Rückwärtsbewegung.',
    'Sichtkontakt nicht einfach voraussetzen.', '9'),
  make('truck-turn','Lkw biegt rechts ab','Große Fahrzeuge',
    'Ein Lkw fährt vor dir und blinkt rechts. Rechts zweigt eine Straße ab.',
    'Der Lkw vor dir schwenkt zunächst etwas nach links, sein rechter Blinker ist eingeschaltet. Sein langer Aufbau braucht Platz zum Rechtsabbiegen.',
    [481,347],[457,355], 'Rechts neben dem Lkw scheint eine Lücke frei zu werden. Wie reagierst du?',
    'Mit Abstand dahinter bleiben und den Abbiegevorgang abwarten.', 'Schnell rechts in die Lücke fahren.', 'Dicht aufrücken, damit der Lkw schneller abbiegt.',
    'Ein langer Lkw kann zum Abbiegen ausholen; seine Hinterräder laufen weiter innen. Der scheinbar freie Raum rechts kann gleich Teil seines Fahrwegs sein.',
    'Denke bei großen Fahrzeugen die gesamte Bewegung mit.', '1'),
  make('emergency','Einsatzfahrzeug nähert sich','Besondere Verkehrslagen',
    'An der nächsten Kreuzung nähert sich von rechts ein Rettungswagen mit Blaulicht und Einsatzhorn. Das Horn wird hier nur im Text beschrieben.',
    'Von rechts fährt ein weiß-oranger Rettungswagen mit blauem Blinklicht auf die Kreuzung zu.',
    [677,300],[535,300], 'Blaulicht und Einsatzhorn sind eingeschaltet. Was tust du?',
    'Verkehr beobachten, kontrolliert verzögern und freie Bahn schaffen.', 'Unverändert weiterfahren, weil deine Straße breiter ist.', 'Ohne Blick auf andere abrupt ausweichen.',
    'Blaulicht zusammen mit Einsatzhorn verlangt, sofort freie Bahn zu schaffen. Handle dabei kontrolliert und gefährde beim Platzmachen keine anderen Menschen.',
    'Platz schaffen braucht Überblick.', '38')
];
